
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CosmeticsShop.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Comment()
    {

        this.Products = new HashSet<Product>();

    }


    public int ID { get; set; }

    public string CommentMsg { get; set; }

    public Nullable<System.DateTime> CommentDate { get; set; }

    public Nullable<int> ProductID { get; set; }

    public Nullable<int> ParentID { get; set; }

    public Nullable<int> UserID { get; set; }

    public Nullable<int> Rate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Product> Products { get; set; }

}

}
